services:
  - type: web
    name: envirointel-ke
    env: python
    runtime: python3
    region: oregon
    plan: free
    buildCommand: |
      echo "Installing frontend dependencies..."
      cd frontend && npm install
      echo "Building React frontend..."
      npm run build
      echo "Creating static directory for backend..."
      mkdir -p ../backend/static
      echo "Copying React build to backend static directory..."
      cp -r build/* ../backend/static/
      echo "Installing Python dependencies..."
      cd ../backend && pip install -r requirements.txt
      echo "Build completed successfully!"
    startCommand: cd backend && python -m uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        value: "MONGO_URL"
      - key: NODE_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
    healthCheckPath: /
    autoDeploy: true
