services:
  - type: web
    name: envirointel-ke
    env: python
    region: oregon
    plan: free
    buildCommand: |
      echo "Installing frontend dependencies..."
      cd frontend && yarn install --frozen-lockfile
      echo "Building React frontend..."
      yarn build
      echo "Creating static directory for backend..."
      mkdir -p ../backend/static
      echo "Copying React build to backend static directory..."
      cp -r build/* ../backend/static/
      echo "Installing Python dependencies..."
      cd ../backend && pip install -r requirements.txt
      echo "Build completed successfully!"
    startCommand: cd backend && python -m uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        value: "mongodb+srv://kendy6lackrose:c32m9bZxaqDjOZHU@cluster0.lql8izk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: NODE_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
    healthCheckPath: /
    autoDeploy: true
